inherit_from: .rubocop_todo.yml

# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

require:
  - ./rubocop/project_cops.rb

AllCops:
  NewCops: enable

Layout/IndentationConsistency:
  EnforcedStyle: normal

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Layout/IndentationWidth:
  Width: 2

Project/ArCallsInViews:
  Enabled: true
  Severity: warning
  Include:
    - 'app/views/**/*.erb'
