require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/order_line_items", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # OrderLineItem. As you add validations to OrderLineItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OrderLineItem.create! valid_attributes
      get order_line_items_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      order_line_item = OrderLineItem.create! valid_attributes
      get order_line_item_url(order_line_item)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_order_line_item_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      order_line_item = OrderLineItem.create! valid_attributes
      get edit_order_line_item_url(order_line_item)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OrderLineItem" do
        expect {
          post order_line_items_url, params: { order_line_item: valid_attributes }
        }.to change(OrderLineItem, :count).by(1)
      end

      it "redirects to the created order_line_item" do
        post order_line_items_url, params: { order_line_item: valid_attributes }
        expect(response).to redirect_to(order_line_item_url(OrderLineItem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OrderLineItem" do
        expect {
          post order_line_items_url, params: { order_line_item: invalid_attributes }
        }.to change(OrderLineItem, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post order_line_items_url, params: { order_line_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested order_line_item" do
        order_line_item = OrderLineItem.create! valid_attributes
        patch order_line_item_url(order_line_item), params: { order_line_item: new_attributes }
        order_line_item.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the order_line_item" do
        order_line_item = OrderLineItem.create! valid_attributes
        patch order_line_item_url(order_line_item), params: { order_line_item: new_attributes }
        order_line_item.reload
        expect(response).to redirect_to(order_line_item_url(order_line_item))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        order_line_item = OrderLineItem.create! valid_attributes
        patch order_line_item_url(order_line_item), params: { order_line_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested order_line_item" do
      order_line_item = OrderLineItem.create! valid_attributes
      expect {
        delete order_line_item_url(order_line_item)
      }.to change(OrderLineItem, :count).by(-1)
    end

    it "redirects to the order_line_items list" do
      order_line_item = OrderLineItem.create! valid_attributes
      delete order_line_item_url(order_line_item)
      expect(response).to redirect_to(order_line_items_url)
    end
  end
end
