require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/rate_plans", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # RatePlan. As you add validations to RatePlan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RatePlan.create! valid_attributes
      get rate_plans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      rate_plan = RatePlan.create! valid_attributes
      get rate_plan_url(rate_plan)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_rate_plan_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      rate_plan = RatePlan.create! valid_attributes
      get edit_rate_plan_url(rate_plan)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RatePlan" do
        expect {
          post rate_plans_url, params: { rate_plan: valid_attributes }
        }.to change(RatePlan, :count).by(1)
      end

      it "redirects to the created rate_plan" do
        post rate_plans_url, params: { rate_plan: valid_attributes }
        expect(response).to redirect_to(rate_plan_url(RatePlan.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RatePlan" do
        expect {
          post rate_plans_url, params: { rate_plan: invalid_attributes }
        }.to change(RatePlan, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post rate_plans_url, params: { rate_plan: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rate_plan" do
        rate_plan = RatePlan.create! valid_attributes
        patch rate_plan_url(rate_plan), params: { rate_plan: new_attributes }
        rate_plan.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the rate_plan" do
        rate_plan = RatePlan.create! valid_attributes
        patch rate_plan_url(rate_plan), params: { rate_plan: new_attributes }
        rate_plan.reload
        expect(response).to redirect_to(rate_plan_url(rate_plan))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        rate_plan = RatePlan.create! valid_attributes
        patch rate_plan_url(rate_plan), params: { rate_plan: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested rate_plan" do
      rate_plan = RatePlan.create! valid_attributes
      expect {
        delete rate_plan_url(rate_plan)
      }.to change(RatePlan, :count).by(-1)
    end

    it "redirects to the rate_plans list" do
      rate_plan = RatePlan.create! valid_attributes
      delete rate_plan_url(rate_plan)
      expect(response).to redirect_to(rate_plans_url)
    end
  end
end
