class AddAutoGeneratedToServiceEvents < ActiveRecord::Migration[8.1]
  def change
    add_column :service_events, :auto_generated, :boolean, default: false, null: false
    add_index :service_events, :auto_generated
  end
end
